### PR TITLE
Adding ability to log full field path in error messages instead of just the most nested key

### PR DESCRIPTION
**Pull request by abroglesc**
Addresses issue #52.

Added an additional test to check for the error message. All tests pass and this logs errors in a more consumable format that prints the full key path.

### CODE REVIEW

**Comment by abroglesc** [comment]
Will fix lint errors

**Comment by abroglesc** [comment]
@bxparks this is ready for review now

**Review by bxparks — APPROVED** [review]
The logic looks pretty good. Always appreciate the unit test.

I think the code can be streamlined considerably by extracting the path generation logic into a helper function, something like:

```python
def json_full_path(base_path, key):
    return f'{base_path}.{key}' if base_path else key
```

But I will do that optimization after merging in your code.

**Comment by broglea** [comment]
Thanks and sounds good! Do you have an estimate on when you think you will publish a new release?

**Pull request merged**
