### PR TITLE
Add support of CSV format

### PR DESCRIPTION
**Pull request by korotkevics**
Hello!

I would love your library to have support of CSV format since then I could use it in a custom script I am writing.

Could you please review my PR? I would be ready to make all the necessary adjustments.

I noticed you left a `TODO` comment suggesting you considered adding support for other formats as well therefore I decided to give it a try.

### CODE REVIEW

**Comment by bxparks** [comment]
Hi, thanks for the PR, I'll take a look at this shortly, like within a day or so.
But I'm curious to know, what caused you add this feature? For a CSV file, the number of columns are fixed and known, so I would have thought that `bigquery-schema-generator` would not be useful. In contrast, JSON data is hierarchical, so new data records can add new columns, which makes this script necessary.

**Comment by korotkevics** [comment]
> Hi, thanks for the PR, I'll take a look at this shortly, like within a day or so.
> But I'm curious to know, what caused you to add this feature? For a CSV file, the number of columns are fixed and known, so I would have thought that `bigquery-schema-generator` would not be useful. In contrast, JSON data is hierarchical, so new data records can add new columns, which makes this script necessary.

Thank you for the prompt reply!
In short,
- it overcomes some general limitations of using a similar functionality in BQ as it states in the description
- it already has BQ data types support built-in which is a big thing
- it has the concept of 'softness' and 'hardness' which I could use to conclude on whether a value needs to have a `REQUIRED` mode (with some extra juggling on my end) :)

**Comment by bxparks** [comment]
Hi, I created a different (shorter) implementation in #26. Can you take a look?
It seems like `csv.DictReader` does pretty much what your CSV adapter does.
Then I inserted a JSON adapter by using a generator.
Once I did those things, most of your code could be just removed (sorry).
I added new unit tests into testdata.txt.

**Comment by korotkevics** [comment]
I'm closing this PR as we continue our discussion in #26

**Pull request closed without merging**
